---
driver:
  name: vagrant
  vm_hostname: roland-test-01

provisioner:
  name: chef_zero

verifier:
  name: inspec
  format: <%= ENV['CI'] ? 'junit' : 'cli' %>
  <% if ENV['CI'] %>
  output: "test-reports/%{platform}/%{suite}_inspec.xml"
  <% end %>

platforms:
  - name: centos-6.9
    driver_config:
      box: bento/centos-6.9
      require_chef_omnibus: true
      customize:
        cpu: 2
        memory: 2048

suites:
  - name: base
    run_list:
      - role[base]
    attributes:
