source 'https://rubygems.org'

gem 'chefspec'
gem 'fauxhai'
gem 'chef'
gem 'rubocop'
gem 'thor-scmversion'
gem 'test-kitchen'
gem 'kitchen-inspec'
gem 'inspec'
gem 'cookbook-development', :git => 'https://github.com/RallySoftware-cookbooks/cookbook-development'
